### ISSUE TITLE
Redesign figuren 1 en 2

### ISSUE THREAD

**Issue by sgort** [MinBZK/LegitiMaat#35]
Figuur 1 en 2 zijn beiden nog in concept. Zij hebben nog een nieuw design nodig.
## Figuur 1
![image](https://user-images.githubusercontent.com/25812095/177204944-30e145c9-136b-4977-8d4a-8273fe2245aa.png)

## Figuur 2
![image](https://user-images.githubusercontent.com/25812095/177204995-0a67ca32-74a2-43ef-829e-80fba61b1956.png)

**Comment by nicorikken** [comment]
Er zijn veel middelen om diagrammen mee te maken. Misschien kan Mermaid worden gebruikt voor gecodeerde diagrammen die gegenereerd kunnen worden en ook direct op GitHub.com zichtbaar zijn door de integratie: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams

**Comment by sgort** [comment]
Niet bekend met voorkeuren per se. Zal het bespreken met de groep en voorleggen aan de designer die nu met de diagrammen bezig is.

**Comment by nicorikken** [comment]
Klinkt goed, ik ben benieuwd.

**Comment by sgort** [comment]
Tot nader order opgelost met redesigned exemplaren.

![voorbereidende-handelingen](https://user-images.githubusercontent.com/25812095/194854411-6b81d3bb-5bcc-4d70-8e07-f9d52fc9b94b.png)

![processen-wetsuitvoering](https://user-images.githubusercontent.com/25812095/194854593-b4fb640a-fdae-49c1-b0f7-3d033c0b6294.png)
